{
 "title": "DevOps Observability Lab - Application Metrics",
 "tags": [
  "devops",
  "observability",
  "prometheus",
  "loki"
 ],
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests in last 1 minute",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 6 },
   "targets": [
    {
     "expr": "sum(increase(app_requests_total[1m]))",
     "legendFormat": "requests/min"
    }
   ]
  },
  {
   "title": "Errors in last 1 minute",
   "type": "stat",
   "gridPos": { "x": 8, "y": 0, "w": 8, "h": 6 },
   "targets": [
    { "expr": "increase(app_errors_total[1m])", "legendFormat": "errors/min" }
   ]
  },
  {
   "title": "Application requests by endpoint/status",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 6, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by (endpoint, status) (increase(app_requests_total[1m]))",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Application errors per minute",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 6, "w": 12, "h": 8 },
   "targets": [
    { "expr": "increase(app_errors_total[1m])", "legendFormat": "errors/min" }
   ]
  }
 ]
}